### ISSUE TITLE
arquivo authors

### ISSUE THREAD

**Issue by rajivbarbosa** [rodrigojulianib/discreta03g03#1]

**Comment by rajivbarbosa** [comment]
Cada um adicione seu nome,depois que todos adicionarem o último fecha o bug

**Comment by rodrigojulianib** [comment]
Já adicionei o meu.

**Comment by victorrolim** [comment]
Já adicionei o meu.

**Comment by rodrigojulianib** [comment]
O arquivo AUTHORS estava dando conflito então o apaguei para reiniciá-lo. Colocarei o nome de todos e darei merge com o master. Farei o Mesmo com o README.
