### ISSUE TITLE
Grupo duplicado?

### ISSUE THREAD

**Issue by drbeco** [rodrigojulianib/discreta03g03#4]
Que repositório é o correto?

https://github.com/Renan-vicente/discreta03g03

https://github.com/rodrigojulianib/discreta03g03

**Comment by JoaoPaacheco** [comment]
O de Rodrigo, professor. Houve um número maior de pessoas querendo criar o repositório do que era necessário, então houveram mais repositórios do que a quantidade de grupos. Renan provavelmente esqueceu de apagar o repositório dele. Além disso o repositório conta apenas com ele.

**Comment by rodrigojulianib** [comment]
Exatamente, o meu repositório é o correto. Obrigado João Pedro!
https://github.com/rodrigojulianib/discreta03g03
